name: Publish Docker image
on: workflow_dispatch
jobs:
  build_and_publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: extract package.json version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Build image and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
          tags: latest,${{ steps.extract_version.outputs.version }},${{ steps.extract_version.outputs.version }}-${{ github.run_number }}
      - name: Print version
        run: echo "${{ steps.extract_version.outputs.version }}-${{ github.run_number }}"